azure-pipelines.yml

This will cause to only run 1 build at a time by batching commits, rather than 1 per commit.

Batch continious integration builds to minimize number of builds

---

script/publish-workers.cmd

Currently, the build outputs workers for netcoreapp2.1\ubuntu16.04-x64 and netcoreapp2.1\ubuntu18.04-x64. Instead of this, just publish worker for netcoreapp2.1\linux-x64.

Publish linux-x64 binaries instead of ubuntu* binaries.

---

README.md

Spark 2.4.2 is recently released and is not compatiable with .NET for Spark. Until the version is supported, we need to point to the Spark distro that is compatible.

Update Spark download link in Getting Started in README.md

---

src/csharp/Microsoft.Spark/Sql/DataFrameWriter.cs

Addresses #55 
Will be adding E2E tests.

DataFrameWriter PartitionBy fails

---

README.md

On Windows, when you use .NET Core 2.1, building the solution will produce a DLL as opposed to an EXE. This means the user would have to pass in the path to dotnet.exe and not the DLL itself.

Updating Readme to reflect the use of dotnet.exe

---

azure-pipelines.yml
eng/Sign.proj

Currently, only the nuget packages are signed. Update build pipieline to sign snupkg packages as well.

Sign snupkg packages during build process

---

README.md
src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/DotnetRunner.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/DotnetRunner.scala

`formatPath()` adds ".\" or "." to the .NET executable. This forces the user to specify a full path for the .NET executable passed to `spark-submit`. For example,
```
spark-submit --class org.apache.spark.deploy.DotnetRunner microsoft-spark-<version>.jar dotnet HelloSpark.dll
```
is not allowed, since `formatPath()` changes `dotnet` to `.\dotnet.exe` even if dotnet is in the PATH.

Remove formatPath() that adds ".\" or "./" to the executable.

---

README.md

This needs to be reverted for now. It will be changed to `dotnet` again when 0.2.0 is released.

Revert README.md on dotnet path

---

src/csharp/Microsoft.Spark/Microsoft.Spark.csproj

<PackageReleaseNotes> will now point to the release notes in GitHub.

Update PackageReleaseNotes for Nuget package

---

src/csharp/Directory.Build.props

Author needs to be "Microsoft". I think this info got lost when we convert from .nuspec to project file.

Add author info and update repository info for Nuget package

---

azure-pipelines.yml
examples/Microsoft.Spark.FSharp.Examples/Microsoft.Spark.FSharp.Examples.fsproj

The VS 2017 F# compiler doesn't like the new AssemblyInformationAttribute added by dotnet/arcade.
Also, rename the signing leg of the build.

Fix VS 2017 build

---

README.md
benchmark/scala/pom.xml
docs/getting-started/ubuntu-instructions.md
docs/getting-started/windows-instructions.md
docs/release-notes/0.3/release-0.3.md
eng/Versions.props
src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
src/csharp/Microsoft.Spark/Sql/SparkSession.cs
src/scala/microsoft-spark-2.3.x/pom.xml
src/scala/microsoft-spark-2.4.x/pom.xml
src/scala/pom.xml

This PR contains changes necessary for releasing v0.3.0.

v0.3.0 release prep

---

src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
src/csharp/Microsoft.Spark.UnitTest/TestUtils/ArrowTestUtils.cs

Now that #134 is checked in, we don't need to have a different logic for worker discovery. (And minor style changes for using `var`)

Remove net461 specific code in E2E tests.

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/TriggerTests.cs
src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamWriter.cs
src/csharp/Microsoft.Spark/Sql/Streaming/Trigger.cs

Support Trigger in DataStreamWriter

---

src/csharp/Microsoft.Spark.Worker.UnitTest/TestData.cs
src/csharp/Microsoft.Spark.Worker/Processor/PayloadProcessor.cs
src/csharp/Microsoft.Spark.Worker/TaskRunner.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs
src/csharp/Microsoft.Spark/Versions.cs

There will be a breaking change for UDF contract due to #135. Now, the worker needs to enforce some kind of versioning check to ensure that Microsoft.Spark.dll is compatible b/w the driver and worker.

Compatibility check for Microsoft.Spark.dll in the worker.

---

benchmark/csharp/Tpch/TpchFunctionalQueries.cs
benchmark/csharp/Tpch/VectorFunctions.cs
examples/Microsoft.Spark.CSharp.Examples/Sql/VectorUdfs.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
src/csharp/Microsoft.Spark.UnitTest/WorkerFunctionTests.cs
src/csharp/Microsoft.Spark.Worker/Command/SqlCommandExecutor.cs
src/csharp/Microsoft.Spark/Microsoft.Spark.csproj

Updating to the latest Arrow version which allows us to simplify some code, and brings in the latest perf fixes.

Update Apache.Arrow reference to v0.14.

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/RuntimeConfigTests.cs
src/csharp/Microsoft.Spark/Sql/RuntimeConfig.cs
src/csharp/Microsoft.Spark/Sql/SparkSession.cs

This PR will allow retrieving and modifying a SparkSessions configuration without requiring a `stop` and recreation of the SparkSession.

Support for SparkSession.conf

---

src/csharp/Microsoft.Spark.UnitTest/AssemblyLoaderTests.cs
src/csharp/Microsoft.Spark.UnitTest/UdfSerDeTests.cs
src/csharp/Microsoft.Spark/Utils/AssemblyLoader.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs

This will enable using --archives udf.zip so that you can put all the udf dlls in one zip file.
You can do this by setting AssemblySearchPathsEnvVarName:
```
export AssemblySearchPathsEnvVarName=./udf.zip
```

Expose a way to override assembly search paths used by AssemblyLoader.

---

script/package-worker.ps1

Only tar.gz was generated for Linux. Generate .zip as well so that it can be used for --archives option.

Generate Microsoft.Spark.Worker-<version>.zip for Linux as well.

---

script/package-worker.ps1

`zip` files created using `Compress-Archive` in powershell causes incorrect behavior when using OSX's `Archiver` to extract.  There is a bug in Powershell module Microsoft.PowerShell.Archive.  This PR will update the module before creating the `zip`.

Package Worker zip fix for Mac OSX

---

benchmark/csharp/Tpch/Tpch.csproj
benchmark/csharp/Tpch/VectorFunctions.intrinsics.cs

When Tpch.csproj is built for netcoreapp3.0, it will use .NET Core 3.0's `Avx` APIs to do 4 double computations at once.
Doing a simple BenchmarkDotNet benchmark of the two implementations:
```C#
public class VectorFunctionsBench
{
private readonly DoubleArray extendedPrice;
private readonly DoubleArray discount;
private readonly DoubleArray tax;
public VectorFunctionsBench()
{
DoubleArray.Builder builder = new DoubleArray.Builder();
for (int i = 0; i < 10_000; i++)
builder.Append(i);
extendedPrice = builder.Build();
builder.Clear();
for (int i = 0; i < 10_000; i++)
builder.Append((i % 5) * .01);
discount = builder.Build();
builder.Clear();
for (int i = 0; i < 10_000; i++)
builder.Append((i % 4) * .01);
tax = builder.Build();
}
[Benchmark]
public DoubleArray ComputeTotal_OneAtATime() => …
```

Add an example of using .NET Core 3.0 hardware intrinsics in a VectorUdf.

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameReaderTests.cs
src/csharp/Microsoft.Spark/Sql/DataFrameReader.cs

In Scala, `DataFrameReader.load()` has 3 overloads:
* `load()`
* `load(path: String)`
* `load(paths: String*)`
Some popular Scala libraries only support particular overloads of this function.
Until now, .Net for Spark always calls `load(path: String*)`, even if no paths or a single path are provided.
This PR changes the C# implementation of `DataFrameReader.Load(params string[] paths)` to call the appropriate Scala overload of `load()` depending on the number of paths provided to the `paths` parameter.
This is related to Issue #229 .

DataFrameReader.Load() calls different Scala overload depending on path count

---

azure-pipelines.yml
script/download-spark-distros.cmd
src/scala/microsoft-spark-2.4.x/pom.xml
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Spark 2.4.4 is released (https://spark.apache.org/news/spark-2-4-4-released.html) and this PR supports the new release.

Support Spark 2.4.4.

---

azure-pipelines.yml
script/download-spark-distros.cmd
src/scala/microsoft-spark-2.3.x/pom.xml
src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Spark 2.3.4 has been just released. This PR includes changes to support the new Spark version.
Fixes #223

Support Spark 2.3.4

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/SparkFilesTests.cs
src/csharp/Microsoft.Spark/SparkFiles.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs

Support [SparkFiles.scala](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/SparkFiles.scala) . This is useful in determining the path of the files added through `SparkContext.addFile()`

Support for SparkFiles

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaFixture.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs

Currently, Delta tests take about 8.5 minutes per supported Spark versions. This change reduces them to about 40 seconds. The configuration to reduce the time is taken from https://github.com/delta-io/delta/pull/113.

Speed up Delta tests

---

src/scala/microsoft-spark-3.0.x/pom.xml
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetRDD.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/JvmBridgeUtils.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
src/scala/microsoft-spark-3.0.x/src/test/scala/com/microsoft/scala/AppTest.scala
src/scala/pom.xml

In preparation for supporting Spark 3.0.0, which will be released in coming months, this PR creates a microsoft-spark-3.0.x module and compiles against Spark 3.0.0-SNAPSHOT.
Note that UDF testing is not performed (it is currently broken since Spark 3.0 broke the contract) and I will create an instruction how to test/develop it against 3.0 in a separate PR.

Creating microsoft-spark-3.0.x project against Spark 3.0.0-SNAPSHOT.

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamReader.cs

This PR does two things:
1. Adds an overload to `DataStreamReader.Load()` that accepts a `path` parameter.  This new overload matches the Spark API documented [here](https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/streaming/DataStreamReader.html#load-java.lang.String-).  Without this overload, DeltaTables can only be read as a stream source by calling `.Option("path", path).Load()` which is verbose and does not match the Scala syntax found in the Delta documentation found [here](https://docs.delta.io/latest/delta-streaming.html#delta-table-as-a-stream-source).
2. Adds an E2E test for basic `DeltaTable` streaming functionality.

DataStreamReader.Load(path) and E2E test for DeltaTable streaming

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaTable.cs

This PR adds full support for new Delta v0.4.0 APIs.
The new APIs are:
* `DeltaTable.ConvertToDelta()`, which does an in-place conversion from Parquet data to DeltaTable.
* `DeltaTable.IsDeltaTable()`, which checks whether or not some data in storage is a DeltaTable.
* `DeltaTable.Alias()`, which is similar to `DeltaTable.As()`.

Support for new Delta v0.4.0 APIs

---

src/scala/microsoft-spark-3.0.x/pom.xml
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetRDD.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/JvmBridgeUtils.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
src/scala/microsoft-spark-3.0.x/src/test/scala/com/microsoft/scala/AppTest.scala
src/scala/pom.xml

This PR creates a new microsoft-spark-3.0.x project for Scala to build against spark-3.0.0-SNAPSHOT.
Most of the files are copied from microsoft-spark-2.4.x project and `pom.xml` is updated to consume 3.0 SNAPSHOT jar files.
Now, when you build the scala project, `microsoft-spark-3.0.x.jar` will be produced. However, the UDF code path is not validated and most likely is broken since the contracts have been changed. These will be addressed in subsequent PRs.

[Scala] microsoft-spark-3.0.x project to build against spark-3.0.0-SNAPSHOT

---

src/scala/microsoft-spark-3.0.x/pom.xml

Consume 3.0.0-preview jars from the Maven repository instead of the SNAPSHOT repository.

[Scala] Use Spark 3.0.0-preview instead of 3.0.0-SNAPSHOT

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
src/csharp/Microsoft.Spark/Sql/SparkSession.cs

`SparkSession.*ActiveSession` APIs uses thread-local variable to store the session. Since the netty server on the JVM side is multi-threaded, the behavior is unexpected.
This also fixes #278.

Remove SparkSession.*ActiveSession APIs

---

docs/building/ubuntu-instructions.md
docs/building/windows-instructions.md

Path to run basic example has not been changed after moving Basic.cs class file to Batch folder in Microsoft.Spark.CSharp.Examples project.

Fix example and path to Basic.cs file in windows-instructions.md and ubuntu-instructions.md

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
src/csharp/Microsoft.Spark/Attributes.cs
src/csharp/Microsoft.Spark/Sql/Functions.cs

This fixes E2E FunctionsTests that are failing for Spark 3.0. because the APIs are either removed or deprecated.
This is a part of the effort to bring in CI for Spark 3.0: #348.

Fix E2E FunctionsTests for Spark 3.0.

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Expressions/WindowTests.cs
src/csharp/Microsoft.Spark/Sql/Expressions/Window.cs
src/csharp/Microsoft.Spark/Sql/Functions.cs

This fixes E2E WindowTests that are failing for Spark 3.0. because the APIs are either removed or deprecated.
This is a part of the effort to bring in CI for Spark 3.0: #348.

Fix E2E WindowTests for Spark 3.0.

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Expressions/WindowSpecTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Expressions/WindowTests.cs
src/csharp/Microsoft.Spark/Sql/Expressions/WindowSpec.cs

This fixes E2E WindowSpecTests that are failing for Spark 3.0. because the APIs are either removed or deprecated.
This is a part of the effort to bring in CI for Spark 3.0: #348.

Fix E2E WindowSpecTests for Spark 3.0

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/SparkContextTests.cs
src/csharp/Microsoft.Spark/SparkContext.cs

This PR addresses #351 , exposing `SparkContext.setLogLevel` API, which helps change log levels programmatically.

Expose SparkContext.setLogLevel API

---

src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
src/csharp/Microsoft.Spark/Sql/Types/DataType.cs

I noticed some areas where the implementation could be made more performant by avoiding using Linq and caching the normalized type names for the simple and complex DataTypes. That way, they don't have to be computed every time. I am not sure if the code paths are perf critical, in which case, I would understand if this PR isn't useful. If that's the case, please let me know.
Also, added a call to use `string.Create` to make normalizing the type names a bit faster (and allocate less). If adding a netstandard2.1 TFM isn't feasible, please let me know and I can revert that part of the change.
The behavior isn't being changed at all, hence existing tests should be sufficient.
``` ini
BenchmarkDotNet=v0.11.5.1159-nightly, OS=Windows 10.0.18362
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 …
```

Precompute the normalized type names of DataTypes and use string.Create on NS2.1 for faster normalization.

---

src/scala/microsoft-spark-2.3.x/pom.xml
src/scala/microsoft-spark-2.4.x/pom.xml
src/scala/microsoft-spark-3.0.x/pom.xml
src/scala/pom.xml

To help reduce the number of touched files during version updates, the individual microsoft-spark-<version> pom.xmls will inherit the version defined in the parent pom.xml

Set the microsoft-spark version only in the parent pom.xml

---

global.json

Internal signing build was failing because the dotnet tool version is updated to support .NET Core 3.1.

Update dotnet tool version to 3.1.100

---

src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

This is preparation for supporting Apache Spark 2.4.5 which should be available this week. The E2E testing was run against RC1 (https://dist.apache.org/repos/dist/dev/spark/v2.4.5-rc1-bin/), so this should be good to go. I will update azure pipeline to run against 2.4.5 once the official version is out.

Support for Apache Spark 2.4.5

---

src/csharp/Microsoft.Spark.E2ETest/Resources/people.json
src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfComplexTypesTests.cs
src/csharp/Microsoft.Spark.Worker/Command/SqlCommandExecutor.cs
src/csharp/Microsoft.Spark/Sql/RowCollector.cs
src/csharp/Microsoft.Spark/Sql/RowConstructor.cs

This is a follow up of #376 and #214 to remove the materialization inside `construct()`. And change it on the worker side. This would make the behavior consistent for UDF that takes in Row and that returns Row.

Follow up on UDF that takes in and returns Row

---

README.md
azure-pipelines.yml
script/download-spark-distros.cmd

Spark 2.4.5 has been just released: https://spark.apache.org/releases/spark-release-2-4-5.html
This PR adds E2E tests with Spark 2.4.5 along with doc updates. Note that jar is updated in #392.

Support for Spark 2.4.5

---

src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Addresses #421 and additionally fixes `logError` to actually print the stack trace from the `Throwable` (previously it printed the object string).
- Added `closeDotnetProcess` for cleaning up the started .NET process
- Added `finally` for cleaning up `DotnetBackend` as well as the .NET process
- Added `logThrowable` for code reuse
- `process.destroy()` vs `process.destroyForcibly()`
- `SIGTERM` sent vs `SIGKILL` sent respectively
- Confirming request to terminate is received inside of .NET when `process.destroy()` is called
- Can be caught via `AppDomain.CurrentDomain.ProcessExit`
- Determined what happens when .NET tries to continue running indefinitely after termination signal
- Another thread interrupt is made by Databricks after ~6 seconds
- I did not test what happens after the …

Fixes #421: Orphaning of DotnetBackend and .NET process in Databricks

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/TypesTests.cs
src/csharp/Microsoft.Spark.E2ETest/Resources/people.json
src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
src/csharp/Microsoft.Spark/Interop/Ipc/PayloadHelper.cs
src/csharp/Microsoft.Spark/Sql/CustomPicklers.cs
src/csharp/Microsoft.Spark/Sql/Row.cs
src/csharp/Microsoft.Spark/Sql/SparkSession.cs
src/csharp/Microsoft.Spark/Sql/Types/ComplexTypes.cs
src/csharp/Microsoft.Spark/Sql/Types/DataType.cs
src/csharp/Microsoft.Spark/Sql/Types/Date.cs
src/csharp/Microsoft.Spark/Sql/Types/SimpleTypes.cs
src/csharp/Microsoft.Spark/Utils/PythonSerDe.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs

This PR exposes `DateType` which will support one of the `DataType` in #26. This PR will also fix #389 and #410. It provides the `DateType` support as below:
1. Support `DataFrame.Collect()` for `DateType`.
2. Support `CreateDataFrame` that takes in `Date`. Please see examples as below.
3. Support UDF that takes in `Date` and UDF that returns `Date`. Please see examples as below.
```csharp
// create df using CreateDataFrame.
var data = new List<GenericRow>();
data.Add(new GenericRow(new object[] { "Alice", new Date(2020, 1, 1) }));
data.Add(new GenericRow(new object[] { "Bob", new Date(2020, 1, 2) }));
var schema = new StructType(new List<StructField>()
{
new StructField("name", new StringType()),
new StructField("date", new DateType())
});
DataFrame df = spark.CreateDataFrame(data, …
```

Support DateType

---

src/csharp/Microsoft.Spark/Interop/SparkEnvironment.cs
src/csharp/Microsoft.Spark/Sql/DataFrame.cs

There are scenarios where Spark version is needed on the driver side to have different logic of processing based on the Spark version (e.g., #414, getting connection info for `Collect`, etc.). This PR proposes to introduce internal `SparkVersion` property for `SparkEnvironment` to make it easy to get Spark version.

Expose internal API to get Spark version on the driver side

---

src/csharp/Microsoft.Spark/SparkContext.cs

This small PR makes sure the `MemoryStream` in `SparkContext` gets disposed.

Dispose MemoryStream

---

src/csharp/Microsoft.Spark/Interop/SparkEnvironment.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs
src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala

This PR adds the `SPARK_VERSION_OVERRIDE` environment variable.
If `SPARK_VERSION_OVERRIDE` is set, it will override the `DOTNET_WORKER_SPARK_VERSION`. For example, if the driver uses Spark version 2.4.1. And `SPARK_VERSION_OVERRIDE` is set to 2.3.1. When running UDF, the job will hang since the version is not matching.
One the other hand, if we want to run Microsoft.Spark.Worker in specific Spark version. The `SPARK_VERSION_OVERRIDE` should be set to match that version. So it can help avoid (patch)version mismatch problems.

Adding SPARK_VERSION_OVERRIDE environment variable

---

src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs
src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala

Currently, when there is a failure on an operation (e.g., `spark.Read().Json(path)` because `path was invalid`), the JVM side pollutes the logs by printing out unnecessary info such as all the methods belonging to a class of the object in action.
This PR proposes to streamline the logging and now it will print out more descriptive one ERROR log line for such a failure:
`20/03/03 17:14:34 ERROR DotnetBackendHandler: Failed to execute 'json' on 'org.apache.spark.sql.DataFrameReader' with args=([Type=scala.collection.mutable.WrappedArray.ofRef, Value: WrappedArray(aslkdf)])`
The C# side logging remains the same, and you can turn on printing "all methods" by setting the log level to DEBUG.

Streamline logging when there is a failure

---

docs/coding-guidelines/csharp-coding-style.md

`dotnet/corefx` has moved to `dotnet/runtime` and the links need to be updated accordingly.

[Documentation] Update csharp-coding-style.md to point to dotnet/runtime

---

azure-pipelines.yml
script/download-worker-release.cmd
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs

This PR adds running E2E tests against the oldest compatible version of Microsoft.Spark.Worker to test backward compatibility. Fixes #453

Adding testing E2E tests against oldest compatible worker version

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/Word2VecModelTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/Word2VecTests.cs
src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
src/csharp/Microsoft.Spark/ML/Feature/Word2Vec.cs
src/csharp/Microsoft.Spark/ML/Feature/Word2VecModel.cs
src/csharp/Microsoft.Spark/Microsoft.Spark.csproj

Hi,
This implements Word2Vec and Word2VecModel so that the Word2Vec example can be completed (see https://spark.apache.org/docs/2.2.0/mllib-feature-extraction.html#word2vec), this is for issue #381 
Thanks,
Ed Elliott

Implement ML Features: Word2Vec

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaFixture.cs

This PR changes `Microsoft.Spark.Extensions.Delta.E2ETest` to use [Delta Lake 0.6.0](https://github.com/delta-io/delta/releases/tag/v0.6.0) JAR when running tests.  This change helps us ensure that our extension is compatible with the latest Delta Lake release.

Run Delta E2ETests with Delta Lake 0.6.0

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
src/csharp/Microsoft.Spark/Sql/SparkSession.cs

Modify the SparkSession.Catalog call from a method to a property.  This helps make the experience similar to scala and python.
Fixes #497

Change SparkSession.Catalog to a property

---

azure-pipelines.yml

Fix the official build pipeline where the master branch (shipping branch) is not explicitly specified.

Fix the official build pipeline

---

azure-pipelines.yml

This PR improves the build pipeline by publishing binlog for each build (for a better debugging) and remove the unnecessary packing for forward compatibility repo.

Improve build pipeline (add binlog and disable unnecessary packing)

---

src/csharp/Microsoft.Spark/Microsoft.Spark.csproj

Just updating the M.D.A dependency to 0.4.0
cc @eerhardt. Tagging @imback82 since I can't add you as a reviewer

Update M.D.A to 0.4.0

---

docs/broadcast-guide.md
docs/udf-guide.md

[DOC] Adding guides to explain UDF serialization and Broadcast variable usage

---

azure-pipelines.yml
script/download-spark-distros.cmd
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Spark 2.4.6 was released recently and we will support it in the next release (0.12).

Support Spark 2.4.6

---

examples/Microsoft.Spark.CSharp.Examples/MachineLearning/Sentiment/Program.cs
examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/Basic.cs
examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/Datasource.cs
examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorDataFrameUdfs.cs
examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs

Fixes #544
Following rename structure suggested by [imback82](https://github.com/dotnet/spark/issues/544#issuecomment-643664224), I'm fixing `AppName` in those examples starting with an invalid character according to the Spark docs. This will allow running the examples using k8s as the resource manager. Using the previous AppNames the executor pods couldn't be created.

Fix AppName in examples to follow Spark naming convention

---

README.md
benchmark/scala/pom.xml
docs/release-notes/0.12/release-0.12.md
eng/Versions.props
src/scala/pom.xml

This PR prepares the v0.12.0 release.

Prep 0.12.0 release

---

src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/AssemblyKernelExtension.cs

The extension attempts to emit the assembly of the previous compilation object.  This works with cases where code submissions have no errors.  However, because we throw an exception if we have already emitted the assembly, if a user submits code that contains an error, then we will hit this exception.
Instead of emitting the previous submission's assembly, first run the code submission, then emit the assembly for the current compilation object.

Bugfix for Microsoft.Spark.Extensions.DotNet.Interactive duplicate file exception

---

src/csharp/Microsoft.Spark.UnitTest/AssemblyLoaderTests.cs
src/csharp/Microsoft.Spark/Utils/AssemblyLoader.cs

`AssemblyLoader.ResolveAssembly` uses `AssemblySearchPathResolver.GetAssemblySearchPaths` to build paths when checking for assemblies.  An assembly was found to exist within one of the built paths, but this was a relative path.  When resolving dotnet core assemblies, `AssemblyLoader.ResolveAssembly` uses `AssemblyLoadContext.Default.LoadFromAssemblyPath` and this requires an `absolute` assembly path.

[Bug] AssemblyLoader should use absolute assembly path when loading assemblies

---

src/csharp/Extensions/README.md
src/csharp/Microsoft.Spark.sln

This small PR adds a `README.md` to the Extension directory.  For now, this file only contains a list of available extensions.  Eventually, it will be expanded to include instructions for how to develop a third-party extension.
I chose to make this a `README.md` and not a doc file in the `docs` directory because I think it is nice to have it immediately available when you look at the `Extensions` directory.  However, if folks feel strongly about moving it to the `docs` folder, I don't mind.

README.md for Extension directory

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaFixture.cs

This PR updates`Microsoft.Spark.Extensions.Delta.E2ETest` to run tests against Delta Lake 0.6.1, which is the latest version of Delta Lake that targets Spark 2.4.x.

Run Delta Lake tests against Delta Lake 0.6.1

---

examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/Basic.cs
examples/Microsoft.Spark.FSharp.Examples/Sql/Basic.fs

Fixes https://github.com/dotnet/spark/issues/600
I think it could be beneficial to show more examples on how to manipulate data frames.
```csharp
DataFrame unionDf = df.Union(df);
unionDf.Show();
+----+-------+
| age|   name|
+----+-------+
|null|Michael|
|  30|   Andy|
|  19| Justin|
|null|Michael|
|  30|   Andy|
|  19| Justin|
+----+-------+
```
```csharp
df.WithColumn("location", Lit("Seattle")).Show();
+----+-------+--------+
| age|   name|location|
+----+-------+--------+
|null|Michael| Seattle|
|  30|   Andy| Seattle|
|  19| Justin| Seattle|
+----+-------+--------+
```
```csharp
df.WithColumnRenamed("name", "fullname").Show();
+----+--------+
| age|fullname|
+----+--------+
|null| Michael|
|  30|    Andy|
|  19|  Justin|
+----+--------+
```
```csharp …
```

Add more Data Frame examples

---

docs/building/ubuntu-instructions.md

Fixes https://github.com/dotnet/spark/issues/602
Errors were encountered on linux where an application binary couldn't be executed due to missing directory name in the command.
To fix the issue, we needed to explicitly specify the directory of the application binary in the executable commands.

Prepend current directory to application binary name in sample commands

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Attributes.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/DeltaLakeVersions.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaMergeBuilder.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaMergeMatchedActionBuilder.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaMergeNotMatchedActionBuilder.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaTable.cs

This PR adds Delta Lake version annotations to all Delta Lake APIs in `Microsoft.Spark.Extensions.Delta`.  Versions were determined according to equivalent annotations found in the [official Delta Lake API docs](https://docs.delta.io/0.6.1/api/scala/io/delta/tables/index.html).
This PR contributes to #618.

Add Delta Lake version annotations to `Microsoft.Spark.Extensions.Delta` APIs.

---

src/csharp/Microsoft.Spark/Sql/ArrowArrayHelpers.cs

https://github.com/dotnet/spark/issues/25
I've found that ```ArrowArrayHelpers.cs``` has type check logics that are redundant
this PR would increase code readability

Reduce trials that getting same object type

---

src/csharp/Microsoft.Spark.Worker.UnitTest/DaemonWorkerTests.cs
src/csharp/Microsoft.Spark.Worker.UnitTest/PayloadProcessorTests.cs
src/csharp/Microsoft.Spark.Worker.UnitTest/TestData.cs

There are a lot of spark versions but only 2.4.0 has been tested.
so I've added test cases, also move test cases to `TestData.cs`
also moved test cases have been reused in `PayloadProcessTests`

Add testcases for spark version

---

azure-pipelines.yml

It appears that E2E forward compatibility tests are missing against Spark 2.4.6. The reason is that 2.4.5 is the latest version that 0.9.0 was tested against. I am adding a comment to `azure-pipeline.yml` not to forget about this (I knew about this during review, but forgot about it after few months).

Update azure-pipeline.yml to include comments on why E2E forward compatibility test does not run against Spark 2.4.6.

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/SerDeTests.cs
src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala

We were previously only returning ASCII strings from JVM=>CLR.  This PR supports encoding the string as UTF-8.

Return UTF-8 encoded string from JVM => CLR

---

azure-pipelines.yml
script/download-spark-distros.cmd
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Spark [2.4.7](https://spark.apache.org/news/spark-2-4-7-released.html) and [3.0.1](https://spark.apache.org/news/spark-3-0-1-released.html) have been recently released, and this PR adds the support for these new releases.

Support Spark 2.4.7 & 3.0.1

---

azure-pipelines.yml
src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfComplexTypesTests.cs
src/csharp/Microsoft.Spark.UnitTest/Sql/TypesTests.cs
src/csharp/Microsoft.Spark.UnitTest/TypeConverterTests.cs
src/csharp/Microsoft.Spark/Sql/PicklingUdfWrapper.cs
src/csharp/Microsoft.Spark/Sql/Row.cs
src/csharp/Microsoft.Spark/Sql/Types/ComplexTypes.cs
src/csharp/Microsoft.Spark/Utils/TypeConverter.cs

Support `ArrayType` and `MapType` usage in `Row`s.
`Pyrolite` unpickles arrays as an `ArrayList`.  An Arraylist is a non-generic collection of objects, which may not be easy to work with.  `Pyrolite` also unpickles dictionaries as `Hashtable`s and this is also a non-generic collection of objects.
This PR allows a user to use `ArrayList` and `Hashtable` or convert them to `Array` and `Dictionary` types.  This conversion, however, will come with a slight performance hit.
ie:
- ArrayList containing strings => string[]
- ArrayList containing ints => int[]
- ArrayList containing Rows => Row[]
- Hashtable containing int keys and int values => Dictionary<int, int>
- etc.
- Rows: Total number of rows `[100, 1M]`
- BatchSize: Number of rows processed in a batch. `[100]`
- Entries: Number of …

Support ArrayType and MapType

---

src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/api/dotnet/CallbackClient.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/api/dotnet/CallbackClient.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/CallbackClient.scala

Add connection back to connection pool after successfully calling callback.  Was accidently removed in commit https://github.com/dotnet/spark/pull/549/commits/95fe7dbe0e0e8a47c4803845fab81871bc3dc29e

CallbackClient - add connection back to pool

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaFixture.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs

This PR proposes to add coverage for Delta E2E tests running under Spark 3.0, by setting few options mentioned in #657:
```
.Option("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
.Option("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
```

Enable more E2E tests for Delta running under Spark 3.0.

---

src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest.csproj
src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest/PackageResolverTests.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/AssemblyKernelExtension.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/Microsoft.Spark.Extensions.DotNet.Interactive.csproj
src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/PackageResolver.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/ResolvedNugetPackage.cs

Update the `Microsoft.Spark.Extensions.DotNet.Interactive` to be compatible with the updated APIs in `Microsoft.Dotnet.Interactive` `1.0.0-beta.20480.3`

Microsoft.Spark.Extensions.DotNet.Interactive - conform to Microsoft.Dotnet.Interactive 1.0.0-beta.20480.3 API changes.

---

src/csharp/Microsoft.Spark.UnitTest/CallbackTests.cs
src/csharp/Microsoft.Spark.Worker.UnitTest/DaemonWorkerTests.cs

Keep references to the client sockets during test execution to prevent garbage collection of the client sockets.
Fixes #685

Fix DaemonWorkerTests.TestsDaemonWorkerTaskRunners and CallbackTests.TestCallbackServer

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamWriterTests.cs

`TestDataStreamWriterTests.TestForeachBatch` has been flaky and it has caused rerunning the entire suite of tests again and again for PRs, slowing down the process. I am disabling this for now while the root cause is being investigated by @suhsteve.

Disable TestDataStreamWriterTests.TestForeachBatch while root cause is being investigated.

---

azure-pipelines.yml

This fixes #672 
To zip files correctly for macOS, we need to install PowerShell module `Microsoft.PowerShell.Archive` > `1.2.3.0`. Currently zipping happens in the signing stage, which runs in `NetCoreInternal-Pool`. However, installing the module is not allowed in `NetCoreInternal-Pool` and we need to request to `dotnet/core-eng` to get it installed. Since the next release date is coming up soon, we will introduce a new "publish" stage, which runs on a pool that allows installing PowerShell module.

[Build] Separate publish stage from signing stage.

---

azure-pipelines-e2e-tests-template.yml
azure-pipelines.yml
script/download-hadoop-utils.cmd
script/download-spark-distros.cmd

I see occasional timeouts in build due to E2E tests taking longer than one hour if they are run on a SKU that's slow.
This PR splits E2E tests based on Spark versions (2.3, 2.4, 3.0, for example).
I didn't attempt to create a template for this because we cannot reuse it when compatibility tests are brought back. We need to revisit creating a template with compatibility tests in mind.

Split E2E test build pipeline

---

azure-pipelines-e2e-tests-template.yml

#697 introduced a bug where e2e extension tests are not being run.
This PR addresses the issue to enable e2e tests for extensions.

Fix issues where extension e2e tests are not being run

---

src/csharp/Microsoft.Spark.Worker.UnitTest/TestData.cs
src/csharp/Microsoft.Spark.Worker/TaskRunner.cs
src/csharp/Microsoft.Spark/Experimental/Sql/SparkSessionExtensions.cs
src/csharp/Microsoft.Spark/Utils/AssemblyInfoProvider.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs
src/csharp/Microsoft.Spark/Versions.cs

From 1.0.0, we enforce [semantic versioning](https://semver.org/), meaning the worker will be compatible only within the same major version.
This PR changes the behavior of the version checking logic on the worker, following the semantic versioning.

Update version check logic on the worker

---

benchmark/README.md
deployment/README.md
docs/building/ubuntu-instructions.md
docs/building/windows-instructions.md
docs/deploy-worker-udf-binaries.md
docs/getting-started/macos-instructions.md
docs/getting-started/ubuntu-instructions.md
docs/getting-started/windows-instructions.md

Update docs related to new Jar name
Related to #728

Update docs related to new Jar name

---

src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

The JVM thread is not properly cleaned up, so there could be executor services still running when the JVM process tries to exit.
If there are executors running, this will prevent the JVM process to exit (behavior only under Ubuntu), leading to a hanging behavior at the end of the run.
This PR proposes to fix this issue by shutting down the thread pool.

Shutdown the JVM thread pool to fix the hanging issue while exiting.

---

src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/AssemblyKernelExtension.cs
src/csharp/Microsoft.Spark.Worker/Utils/AssemblyLoaderHelper.cs
src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs
src/csharp/Microsoft.Spark/Services/ConfigurationService.cs
src/csharp/Microsoft.Spark/Services/IConfigurationService.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs

Each code submission processed by `dotnet-interactive` run on an available thread in its thread pool.  This means that if two separate code submissions were submitted, each may run on a different thread in the CLR, which in turn be processed on a different thread in the JVM.
This PR prevents this from occurring by forcing the same JVM thread to process all incoming requests from the CLR when running a `dotnet-interactive` repl session.

Isolate all dotnet-interactive statements to use the same jvm thread

---

script/package-worker.ps1

`tar` treats `:` as remote storage, the current `tar` fails with:
```
tar (child): Cannot connect to D: resolve failed
```
Specifying `--force-local` fixes the issue.

Fix package-worker.ps1 to handle output path with ":"

---

src/csharp/Microsoft.Spark.UnitTest/TestUtils/ArrowTestUtils.cs

Improves the readability using c# pattern matching
#25

Use pattern matching in arrow test utils to improve readability

---

docs/migration-guide.md

Angle brackets in `<version>` were not rendering correctly.  Surround them with backticks instead.

migration guide typo

---

src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala

Fixes #751 
This PR fixes signer information mismatch issue for `org.apache.spark.internal.config.Dotnet` by moving the package into `org.apache.spark.internal.config.dotnet`; this will avoid conflicting signer information.

Fix signer information mismatch issue

---

src/csharp/Microsoft.Spark.UnitTest/CallbackTests.cs
src/csharp/Microsoft.Spark/Interop/Ipc/CallbackConnection.cs

Instead of checking that reading from the socket throws an exception, check `CallbackConnection` to verify if it is running instead.
Cancelling the `CancellationToken` changes the _isRunning flag on the `CallbackConnection` from true to false.  Testing that this flag has been set correctly is the right thing to verify versus checking communication states/exceptions while trying to read the socket streams.

Fix flaky CallbackTests.TestCallbackHandlers Test

---

src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs

Fixes #758 
The current code causes a NullReferenceException when the assembly cannot be found so this switches the logic slightly and also adds some additional detail to describe how the DOTNET_ASSEMBLY_SEARCH_PATHS environment variable is set to help users understand why their dll's are not being loaded.
I wasn't sure on writing a test for this, if it needs a test let me know, I did think about adding a check for a FileNotFoundException for a file that doesn't exist and call `UdfSerDe.Deserialize(UdfData udfData)`.
I was also unsure what to throw if the assembly had been loaded but the type couldn't for some reason, I went with TypeLoadException but let me know if you think something else is more appropriate.
The point of this really is that I have seen this pop up a few times and the …

Check whether file is found before trying to dereference it

---

docs/getting-started/macos-instructions.md

Add instructions on setting permissions and removing quarantine attribute
Fixes #762
As long as we don’t have an installer for Microsoft.Spark.Worker, providing instructions to fix the issue manually is the best we can do.

fix macOS Catalina Permissions #762

---

NuGet.config
eng/common/SetupNugetSources.ps1
eng/common/SetupNugetSources.sh
eng/common/darc-init.ps1
eng/common/darc-init.sh
eng/common/sdl/packages.config
eng/common/templates/job/execute-sdl.yml
eng/common/templates/post-build/common-variables.yml
eng/common/templates/post-build/post-build.yml
eng/common/tools.ps1

The `MyGet` feed has been deprecated and tool publishing moved the `new pkgs.dev.azure.com`, causing build failures. Upgrade arcade files to the latest from `release/3.x` branch to fix the issue.
This PR also removes `dotnet-try` feed defined in `Nuget.config` since the new feed already exists as `dotnet-tools`.

Upgrade dotnet/arcade to fix the deprecated feed issue.

---

deployment/HDI-Spark/Notebooks/install-interactive-notebook.sh

The old feed for `dotnet-try` is deprecated. This PR proposes to update the feed for `install-interactive-notebook.sh`.

Update dotnet-try feed for install-interactive-notebook.sh

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/HyperspaceFixture.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/HyperspaceTests.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace/Hyperspace.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace/HyperspaceVersions.cs

This PR adds full support for [Hyperspace 0.4.0](https://github.com/microsoft/hyperspace/releases/tag/v0.4.0).  This includes new APIs `optimizeIndex()` and `index()` introduced in Hyperspace 0.3.0 and 0.4.0, respectively.

Support for Hyperspace 0.4.0

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaFixture.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/DeltaLakeVersions.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaTable.cs

This small PR adds support for Delta Lake 0.8.0.  This includes a new API `DeltaTable.UpgradeTableProtocol()`.

Support for Delta Lake 0.8.0

---

azure-pipelines.yml
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameWriterTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamReaderTests.cs
src/csharp/Microsoft.Spark.Worker/Processor/CommandProcessor.cs
src/csharp/Microsoft.Spark.Worker/Processor/TaskContextProcessor.cs
src/csharp/Microsoft.Spark/Broadcast.cs
src/csharp/Microsoft.Spark/Sql/DataFrame.cs
src/csharp/Microsoft.Spark/Versions.cs
src/scala/microsoft-spark-3-0/pom.xml
src/scala/pom.xml

Add support for Spark 3.1.1 #811
- Update pom.xml and add 3-1 module
- Skip [incompatible delta tests](https://github.com/delta-io/delta/issues/594)
- update azure-pipeline.xml and add 3.1.1 to pipeline
- update [DataFrameWriter](https://github.com/apache/spark/blob/bb9abb098a1e26c220546616d655380c479b0e42/sql/core/src/main/scala/org/apache/spark/sql/DataFrameWriter.scala#L289) and [DataStreamReader](https://github.com/apache/spark/blob/bb9abb098a1e26c220546616d655380c479b0e42/sql/core/src/main/scala/org/apache/spark/sql/DataFrameReader.scala#L259) test order due to change in settings with api behavior.
- Relaxed 3.x version check in `CommandProcessor`, `TaskContextProcessor`, `Broadcast`, `DataFrame`

Support Spark 3.1.1

---

src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
src/scala/microsoft-spark-2-3/src/test/scala/org/apache/spark/util/dotnet/UtilsTest.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
src/scala/microsoft-spark-2-4/src/test/scala/org/apache/spark/util/dotnet/UtilsTest.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
src/scala/microsoft-spark-3-0/src/test/scala/org/apache/spark/util/dotnet/UtilsTest.scala
src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
src/scala/microsoft-spark-3-1/src/test/scala/org/apache/spark/util/dotnet/UtilsTest.scala

Add a new spark conf, `spark.dotnet.ignoreSparkPatchVersionCheck`.  If set to true, then only check the major.minor `SPARK_VERSION` and ignore patch version.  If set to false, then check the `SPARK_VERSION` against the set of `supportedSparkVersions`

Add spark.dotnet.ignoreSparkPatchVersionCheck conf to ignore patch version in DotnetRunner

---

src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
src/csharp/Microsoft.Spark.UnitTest/ConfigurationServiceTests.cs
src/csharp/Microsoft.Spark/Services/ConfigurationService.cs

Update how the `ConfigurationService.GetWorkerExePath` is constructed.
Add a new environment variable, `DOTNET_WORKER_<ver>_DIR` where `ver` can be any of the following (built using the version of the `Microsoft.Spark` assembly):
- major_minor_build
- major_minor
- major
The above listing will take precedence when constructing the worker path (higher item has more precedence).  If it is not set, then fall back to original behavior (use `DOTNET_WORKER_DIR` if it is set, otherwise return the worker process name and expect it to exist in `PATH`).

Add DOTNET_WORKER_<ver>_DIR environment variable

---

azure-pipelines.yml
src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
src/csharp/Microsoft.Spark.UnitTest/Sql/TimestampTests.cs
src/csharp/Microsoft.Spark/Sql/Types/Timestamp.cs

Currently the following evaluates to `false`
```csharp
var dateTimeObj = new DateTime(2021, 01, 01);
new Timestamp(DateTime.Parse(new Timestamp(dateTimeObj).ToString())).Equals(new Timestamp(dateTimeObj))
```
This PR addresses this by updating the `Timestamp.ToString` method to include the UTC timezone information; by adding `Z` to the string format.

Add 'Z' to the string format in Timestamp.ToString() to indicate UTC time.

---

azure-pipelines.yml
src/scala/pom.xml

This PR proposes to temporarily disable the support for `Spark 3.1.1` to release `.NET for Apache Spark 1.1` first to include bug fixes, features that better handle compatibilities, etc.
Once `1.1` is released, we will enable the support for `Spark 3.1.1` and move to `.NET for Apache Spark 2.0` because there are breaking changes for backward compatibility.

Temporarily disable support for Spark 3.1.1 to release .NET for Apache Spark 1.1

---

azure-pipelines.yml
src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
src/csharp/Microsoft.Spark.UnitTest/Sql/TimestampTests.cs
src/csharp/Microsoft.Spark/Sql/Types/Timestamp.cs

Revert "Add 'Z' to the string format in Timestamp.ToString() to indicate UTC time."

---

README.md
benchmark/scala/pom.xml
docs/release-notes/1.1.1/release-1.1.1.md
eng/Versions.props
src/scala/pom.xml

This PR prepares 1.1.1 release, re-release of 1.1.0 after reverting forward compatibility breaking change: #871.

Prep 1.1.1 release

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamReaderTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamWriterTests.cs
src/csharp/Microsoft.Spark.E2ETest/Utils/SQLUtils.cs
src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamReader.cs
src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamWriter.cs
src/csharp/Microsoft.Spark/Versions.cs

PR adds support for the following APIs added in Spark 3.1.0:
**DataStreamReader**
```scala
def table(tableName: String): DataFrame
```
**DataStreamWriter**
```scala
def toTable(tableName: String): StreamingQuery
```

Spark 3.1.0 APIs - DataStreamReader and DataStreamWriter 

---

azure-pipelines.yml
src/scala/pom.xml

Reverts dotnet/spark#870
This revert enables support for Spark 3.1.1.

Revert "Temporarily disable support for Spark 3.1.1 to release .NET for Apache Spark 1.1"

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
src/csharp/Microsoft.Spark/Sql/DataFrame.cs
src/csharp/Microsoft.Spark/Versions.cs

PR adds support for the following APIs added in Spark 3.1.0:
**DataFrame**
```scala
def unionByName(other: Dataset[T], allowMissingColumns: Boolean): Dataset[T]
def sameSemantics(other: Dataset[T]): Boolean
def semanticHash(): Int
```
Added into scala in Spark 2.0.0, but added into pySpark in Spark 3.1.0
```scala
def inputFiles: Array[String]
```

Spark 3.1.0 APIs - DataFrame

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
src/csharp/Microsoft.Spark/Sql/Functions.cs
src/csharp/Microsoft.Spark/Versions.cs

PR adds support for the following APIs added in Spark 3.1.0:
**Functions**
```scala
def percentile_approx(e: Column, percentage: Column, accuracy: Column): Column
def nth_value(e: Column, offset: Int, ignoreNulls: Boolean): Column
def nth_value(e: Column, offset: Int): Column
def acosh(e: Column): Column
def acosh(columnName: String): Column
def asinh(e: Column): Column
def asinh(columnName: String): Column
def atanh(e: Column): Column
def atanh(columnName: String): Column
def assert_true(c: Column): Column
def assert_true(c: Column, e: Column): Column
def raise_error(c: Column): Column
def timestamp_seconds(e: Column): Column
def slice(x: Column, start: Column, length: Column): Column
```

Spark 3.1.0 APIs - Functions

---

azure-pipelines.yml
src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
src/csharp/Microsoft.Spark.UnitTest/Sql/TimestampTests.cs
src/csharp/Microsoft.Spark/Sql/Types/Timestamp.cs

Reverts dotnet/spark#873
Reverting the revert to enable the fix again for 2.0 preparation.

Revert "Revert "Add 'Z' to the string format in Timestamp.ToString() to indicate UTC time.""

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/CatalogTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
src/csharp/Microsoft.Spark/Sql/Catalog/Catalog.cs

PR adds support for the following APIs added in Spark 3.1.0 and adds missing `createTable` APIs:
**Catalog**
Introduced in Spark 3.1.0
```scala
def createTable(tableName: String, source: String, description: String, options: Map[String, String]): DataFrame
def createTable(tableName: String, source: String, schema: StructType, description: String, options: Map[String, String]): DataFrame
```
Missing createTable APIs
```scala
def createTable(tableName: String, source: String, options: Map[String, String]): DataFrame
def createTable(tableName: String, source: String, schema: StructType, options: Map[String, String]): DataFrame
```

Spark 3.1.0 APIs - Catalog

---

docs/release-notes/1.1.1/release-1.1.1.md

The v1.1.1 README has typo for jar versions.

Update README for v1.1.1 for jars

---

src/csharp/Microsoft.Spark.E2ETest/Hadoop/FileSystemTests.cs
src/csharp/Microsoft.Spark/Hadoop/Fs/FileSystem.cs

This PR adds the exists(string filePath) api to the FileSystem, which will allow the users to check whether a given folder or file exists in the file system or not.
I'll be adding more methods once I know, that I have done this work correctly.
**Example: Check for an existing file**
```cs
SparkSession spark = ....
FileSystem fs = FileSystem.Get(spark.SparkContext.HadoopConfiguration());
bool fileExists = fs.Exists("abfss://container@datalake.dfs.core.windows.net/myfolder/file.csv");
```
This PR relates to #328

Added the exists method to the FileSystem.

---

src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/AssemblyKernelExtension.cs

The DotnetInteractive extension creates a temp directory to store dlls and nuget packages and registers this temp directory with the DotnetInteractive kernel for disposal.
This PR adds a new ENV variable to control whether this tmp directory should be registered for disposal.

Extensions.DotNet.Interactive - Add ENV to control disposal of tmp dir

---

azure-pipelines.yml
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Add support for Spark 2.4.8/3.1.2 and add an E2E tests for these new supported Spark versions.

Support for Spark 2.4.8 and Spark 3.1.2

---

deployment/HDI-Spark/Notebooks/install-interactive-notebook.sh

This PR backports PR #808 
---
The old feed for `dotnet-try` is deprecated. This PR proposes to update the feed for `install-interactive-notebook.sh`.

Update dotnet-try feed for install-interactive-notebook.sh (#808)

---

azure-pipelines-e2e-tests-template.yml

Migrate to 1ES hosted pools. This PR update the pipeline yaml to use new pools.
Tracking issue: dotnet/core-eng#14276

Migrate to 1ES hosted pools

---

azure-pipelines.yml

We've officially decommissioned the old BuildPools (see partners mail) in favor of 1ES hosted pools. This change moves dotnet/spark appropriately.

Switch to 1ES hosted pools on main

---

azure-pipelines-e2e-tests-template.yml
src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs

This PR backports PR #1007 
---
This PR fixes the build pipeline due to the following issues:
- Spark 24 < 2.4.8, Spark3.0 < 3.0.3, and Spark31 < 3.1.2 use bintray repository for spark-packages and the repository no longer available.

Fix build pipeline due to bintray no longer available as spark-package repository in v1.0.1 (#1007)

---

src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/deploy/dotnet/DotNetUserAppException.scala
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotNetUserAppException.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/deploy/dotnet/DotNetUserAppException.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala

This PR backports PR #1047
---
Currently in dotnet spark, if the dotnet application exits with error code, SparkUserAppException is thrown. Adding capability to throw a new custom exception (DotNetUserAppException) with the error code and error message. This will be helpful in debugging applications.
Before this change:
22/04/18 17:31:34 INFO CodeGenerator: Code generated in 15.5581 ms
+----+-------+
| age|   name|
+----+-------+
|null|Michael|
|  30|   Andy|
|  19| Justin|
+----+-------+
Unhandled exception. System.Exception: My custom Exception
at HelloSpark.Program.Main(String[] args) in C:\Users\kalamu\source\repos\HelloSpark\HelloSpark\Program.cs:line 14
22/04/18 17:31:35 INFO DotnetRunner: Closing DotnetBackend
22/04/18 17:31:35 INFO DotnetBackend: Callback server has already been …

Capture dotnet application error stack trace (#1047)

---

azure-pipelines.yml

Backporting PRs #1021 and #1030.
--
We've officially decommissioned the old BuildPools (see partners mail) in favor of 1ES hosted pools. This change moves dotnet/spark appropriately.

Switch to 1ES hosted pools on release/branch-1.0 (#1021)(#1030)

---

docs/release-notes/1.0.2/release-1.0.2.md

This PR updates the 1.0.2 release notes with [latest commit](https://github.com/dotnet/spark/commit/9c90c8246d70b3fa8ec6f00567f2c04a705bdae9)

Update v1.0.2 release notes

---

src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs

This PR address issue #1060 by doing the following:
- moved field usage of _socketSemaphore to a single method, vs cross-method ensuring that one method has strict acquire/release semantics and that no other calls to GetConnection(), even inadvertently could ever mess with the semaphore
- Moved semaphore Wait() call to the first method of the try/finally so that it gets called no matter what
- I added an ifnull check around _sockets.Enqueue(socket), just to be extra safe as well in the finally block.
I have tested this using a fairly large project that was exhibiting the error (See the bug) but I'm unsure of how to write an automated test around the original failure scenario without adding some API abstractions around the semaphore lock itself and making something like …

JvmBridge semaphore fix

---

README.md

This PR fixes the README release link tag for releasing the new v1.0.2 release.

Fixes the README release link tag for releasing the new v1.0.2 release

---

azure-pipelines-e2e-tests-template.yml
azure-pipelines.yml

The `windows-2016` pool is being deprecated, and pipelines were failing with the following error:
```
This is a scheduled windows-2016 brownout. The windows-2016 environment is deprecated and will be removed on June 30, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5403
,##[error]The remote provider was unable to process the request.
```
Hence, this PR updates the pool agents to use `windows-2019`.

Update windows pool due to scheduled brownout

---

azure-pipelines-e2e-tests-template.yml
azure-pipelines.yml

Fix build pipeline: Rename service connection from dotnet -> public and update public pool name

---

docs/building/ubuntu-instructions.md

The URL in the tutorial does not resolve. I went to https://maven.apache.org/download.cgi and edited the link for the current version to get the 3.6.3 `.tar.gz` in the commit. Alternatively, that page also leads to the [archives](https://archive.apache.org/dist/maven/maven-3/), where 3.6.3 can be downloaded from https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz.
I hope this was trivial enough to not warrant a separate issue.

Update maven download link

---

azure-pipelines-e2e-tests-template.yml
eng/waitForDpkg.sh

Trying out a fix for the CI issue that's surfacing as:
```
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable) 
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it? 
```
When running `apt` commands.  As seen here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=126859&view=logs&j=6275ae02-8f8b-5df6-73dc-1bd6a4ec92dd&t=bfb24330-1904-5583-de8c-be2e1157559c&l=29

Wait before running apt command

---

src/scala/microsoft-spark-3-2/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

3.2.2 has been out for almost 4 months, and 2 months ago @Niharikadutta mentioned that support for it is being worked on here. What's the status of this? GCP Dataproc Serverless now cannot be run with Spark 3.2.1 (See [Dataproc Serverless Spark runtime releases](https://cloud.google.com/dataproc-serverless/docs/concepts/versions/spark-runtime-versions)).
I'm not very familiar with this codebase so I don't really expect this PR to merge as-is, but I can get a basic Spark program to run on 3.2.2 by simply allowing it without any other changes...
Fixes #1095

At least allow Spark 3.2.2 to be used

---

benchmark/scala/pom.xml
src/csharp/Microsoft.Spark.Worker.UnitTest/DaemonWorkerTests.cs
src/csharp/Microsoft.Spark.Worker/DaemonWorker.cs
src/scala/microsoft-spark-2-4/pom.xml
src/scala/microsoft-spark-3-3/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
src/scala/pom.xml

ref https://stackoverflow.com/questions/41754260/issues-with-scala-tools-org-and-goodstuff-im
scala-maven-plugin is available on maven central and jcenter.
related issue https://github.com/dotnet/spark/issues/1200

fix: remove scala-tools.org from pom.xml due to shutdown of scala-tools.org repository

---

src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest.csproj
src/csharp/Microsoft.Spark.E2ETest.ExternalLibrary/ExternalClass.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/BroadcastTests.cs
src/csharp/Microsoft.Spark.E2ETest/Microsoft.Spark.E2ETest.csproj
src/csharp/Microsoft.Spark.UnitTest/BinarySerDeTests.cs
src/csharp/Microsoft.Spark.UnitTest/Microsoft.Spark.UnitTest.csproj
src/csharp/Microsoft.Spark.UnitTest/UdfSerDeTests.cs
src/csharp/Microsoft.Spark.Worker.UnitTest/CommandExecutorTests.cs
src/csharp/Microsoft.Spark.Worker.UnitTest/Microsoft.Spark.Worker.UnitTest.csproj
src/csharp/Microsoft.Spark.Worker/Command/RDDCommandExecutor.cs
src/csharp/Microsoft.Spark.Worker/Microsoft.Spark.Worker.csproj
src/csharp/Microsoft.Spark.Worker/Processor/BroadcastVariableProcessor.cs
src/csharp/Microsoft.Spark/Broadcast.cs
src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
src/csharp/Microsoft.Spark/RDD/Collector.cs
src/csharp/Microsoft.Spark/SparkContext.cs
src/csharp/Microsoft.Spark/Utils/BinarySerDe.cs
src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs
src/csharp/Microsoft.Spark/Utils/DependencyProviderUtils.cs

This PR replaces `BinaryFormatter` serialization with the `MessagePack` library.  
I was unable to contribute to https://github.com/dotnet/spark/pull/1166, so I’ve opened a new one.  
Replacing `BinaryFormatter` addresses a range of issues, including:  
- **.NET 9 compatibility:** Upgrading to .NET 9 requires a separate NuGet package, but this package is incompatible with .NET Framework 4.8, which is also targeted by the project.  
- **Dotnet.Interactive incompatibility:** Using Dotnet.Interactive result in a smth like BinarySerializationDisabled exception. The only workaround currently is adding:  
```csharp
AppContext.SetSwitch("System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization", true);
``` 
to the beginning of the notebook.  It doesn't work each time, it's hard to …

Migrated to MessagePack instead of BinaryFormatter

---

src/csharp/Microsoft.Spark/Microsoft.Spark.csproj

We use prelease version 3.0.214-rc.1 for MessagePack and it block the Microsoft.Spark to use release version, disable the warning to release Microsoft.Spark.

Disable warning NU5104 for MessagePack
