dotnet/spark

azure-pipelines.yml
eng/Sign.proj
eng/Tools.proj

Here is a example build:
https://dnceng.visualstudio.com/internal/_build/results?buildId=167505
For easier reviewing disable spaces in the diff setting
cc: @danmosemsft @eerhardt @rapoth @imback82

Add signing to worker, spark binaries and nuget packages

---

README.md

Updating the Readme to reflect the JIRA link and Nuget ETA

Updating to reflect JIRA link and Nuget ETA

---

benchmark/csharp/Tpch/Program.cs
benchmark/scala/src/main/scala/com/microsoft/tpch/App.scala
benchmark/scala/src/main/scala/com/microsoft/tpch/TpchFunctionalQueries.scala

TPCH Benchmark fixes

---

README.md

Updated .NET Core version to 2.1 instead of 3.0 to reflect consistency.

Updating README to reflect correct .NET Core version

---

examples/Microsoft.Spark.FSharp.Examples/Program.fs

I've tidied up the F# example app discovery code so that it is more in keeping with F# idioms.

Make F# example app more idiomatic

---

src/csharp/Directory.Build.props

Hide the 3rd party notice in the solution explorer

---

src/csharp/Directory.Build.props

Add LICENSE file to Nuget package

---

README.md

Malformed GET parameters directed browser to the wrong pipeline.

Fix URL to Azure pipeline

---

deployment/install-worker.sh

This PR brings changes to accommodate versioning in our releases.

Worker installation script changes to deal with versioning

---

README.md
docs/release-notes/0.2/release-0.2.md

Now that v0.2.0 is released, README.md can be updated to reflect the v0.2.0 feature.

Update README.md / Release Notes for v0.2.0

---

README.md

Fix the spark-submit usage in README.md.

---

eng/AfterSolutionBuild.targets

Produce Microsoft.Spark.Worker binaries for MacOS.

---

deployment/README.md

There have been few confusions on the arguments when submitting a job to Databricks. This addresses common issues (#142, #121).

[DOC] Update Databricks instruction

---

src/csharp/Microsoft.Spark.Worker/TaskRunner.cs

This will enable #145.
The documentation on HowTo will be tracked with #151.

Add a hook to launch a debugger from the worker process.

---

benchmark/csharp/Tpch/Program.cs
benchmark/run_csharp_benchmark.sh
deployment/README.md
docs/building/ubuntu-instructions.md
docs/building/windows-instructions.md
docs/developer-guide.md
docs/getting-started/ubuntu-instructions.md
docs/getting-started/windows-instructions.md
src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala

Resolve signer issue by moving DotnetRunner to different package name.

---

README.md
benchmark/scala/pom.xml
docs/release-notes/0.3/release-0.3.md
docs/release-notes/0.4/release-0.4.md
eng/Versions.props
src/scala/microsoft-spark-2.3.x/pom.xml
src/scala/microsoft-spark-2.4.x/pom.xml
src/scala/pom.xml

0.4.0 Release

---

src/csharp/Microsoft.Spark.UnitTest/Sql/TypesTests.cs
src/csharp/Microsoft.Spark/Sql/Types/ComplexTypes.cs

Implement MapType in ComplexTypes.cs

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Microsoft.Spark.Extensions.Delta.csproj
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaMergeBuilder.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaTable.cs

This is a simple PR that sets `<IsPackable>true</IsPackable>` for the Delta extension.

Enable IsPackable for Microsoft.Spark.Extensions.Delta 

---

README.md
benchmark/scala/pom.xml
docs/release-notes/0.5/release-0.5.md
eng/Versions.props
src/scala/microsoft-spark-2.3.x/pom.xml
src/scala/microsoft-spark-2.4.x/pom.xml
src/scala/pom.xml

Preparing for the v0.5.0 release.

Release v0.5.0

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
src/csharp/Microsoft.Spark/Sql/RelationalGroupedDataset.cs

This PR exposes GroupBy().Sum() .  Addressses issue #260

Support GroupBy().Sum()

---

src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamWriterTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/TriggerTests.cs
src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamWriter.cs

Expose `DataStreamWriter.PartitionBy()` along with `DataStreamWriter` tests.

Expose DataStreamWriter.PartitionBy().

---

docs/release-notes/0.5/release-0.5.md

The jar version wasn't incremented in the readme

Update release-0.5.md to reference 0.5.0 of the jars

---

docs/coding-guidelines/new-functions.md
docs/contributing.md

- [-] There's associated issues. All PR's should have issue(s) associated - unless a trivial self-evident change such as fixing a typo. You can use the format `Fixes #nnnn` in your description to cause GitHub to automatically close the issue(s) when your PR is merged.
Hi,
I thought it would be helpful to start documenting what is required to implement new functions, I think this is right from the pr's that I have done so far.
ed

documenting minimum requirements for implementing spark api's

---

README.md
benchmark/scala/pom.xml
docs/building/ubuntu-instructions.md
docs/building/windows-instructions.md
docs/release-notes/0.6/release-0.6.md
eng/Versions.props
src/scala/microsoft-spark-2.3.x/pom.xml
src/scala/microsoft-spark-2.4.x/pom.xml
src/scala/pom.xml

Release 0.6.0

---

docs/developer-guide.md

This PR adds an instruction on how to debug UDF in a Spark application.

[Documentation] UDF debugging instruction

---

src/csharp/Microsoft.Spark/Sql/Builder.cs

Add default spark conf for Spark .NET applications.

Add default spark conf for Spark .NET applications

---

README.md
benchmark/scala/pom.xml
docs/building/ubuntu-instructions.md
docs/building/windows-instructions.md
docs/deploy-worker-udf-binaries.md
docs/release-notes/0.7/release-0.7.md
eng/Versions.props
src/scala/microsoft-spark-2.3.x/pom.xml
src/scala/microsoft-spark-2.4.x/pom.xml
src/scala/microsoft-spark-3.0.x/pom.xml
src/scala/pom.xml

This PR prepares the v0.7.0 release.

Prep 0.7.0 release

---

src/csharp/Microsoft.Spark/Services/ConfigurationService.cs

Contributing: Fix a typo

---

README.md
benchmark/scala/pom.xml
docs/release-notes/0.8/release-0.8.md
eng/Versions.props
src/scala/pom.xml

This PR prepares the v0.8.0 release.

Prep 0.8.0 release

---

eng/common/tools.ps1
src/csharp/Microsoft.Spark/Sql/Column.cs

Contributing: fix typos

---

src/csharp/Microsoft.Spark.Worker.UnitTest/TaskRunnerTests.cs

Related to the [following feedback](https://github.com/dotnet/spark/pull/379#discussion_r378445783) in the following PR  #379

nit: Adding DaemonWorkerTests 

---

README.md
benchmark/scala/pom.xml
docs/release-notes/0.10/release-0.10.md
eng/Versions.props
src/scala/pom.xml

This PR prepares the v0.10.0 release.

Prep 0.10.0 release 

---

src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Revert "Support running an C# executable under a directory"

---

src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Creating this duplicate PR of #440 to be merged once the committer issue is fixed.

Support running an C# executable under a directory-Dupe

---

docs/coding-guidelines/add-types-to-SerDe.md

Document to describe how to add a new data type to the SerDe process (was previously https://github.com/dotnet/spark/pull/391)

doc to describe how to add additional types to the SerDe process

---

examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorDataFrameUdfs.cs
examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs

Clean the Vector Udf examples so they are more "apples to apples" comparison.
/cc @bamurtaugh

Clean up vector UDF examples.

---

docs/building/ubuntu-instructions.md
docs/building/windows-instructions.md

Fix build documents Scala project link

Fix build documents Scala project link

---

benchmark/csharp/Tpch/TpchFunctionalQueries.cs
benchmark/csharp/Tpch/VectorDataFrameFunctions.cs
eng/Versions.props
examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorDataFrameUdfs.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
src/csharp/Microsoft.Spark.UnitTest/CommandSerDeTests.cs
src/csharp/Microsoft.Spark.UnitTest/WorkerFunctionTests.cs
src/csharp/Microsoft.Spark.Worker.UnitTest/CommandExecutorTests.cs
src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
src/csharp/Microsoft.Spark/Sql/ArrowArrayHelpers.cs
src/csharp/Microsoft.Spark/Utils/UdfUtils.cs

This can be reviewed now.
Old:
This is WIP. I just have it up here for initial review. 4 things need to happen before this can come out of WIP:
1) https://github.com/dotnet/corefxlab/pull/2885 needs to go in - Done
2) We need to make a 0.3.0 for Microsoft.Data.Analysis - Done
3) 0.3.0 has to go on to Nuget officially - Done
3) The first commit in this PR has to be reverted and the MDA dependency in Spark.csproj needs to be updated to 0.3.0 - Done
@eerhardt

Refactor the DataFrame APIs to use the latest versions where possible

---

src/csharp/Extensions/Microsoft.Spark.Extensions.Azure.Synapse.Analytics/Microsoft.Spark.Extensions.Azure.Synapse.Analytics.csproj
src/csharp/Extensions/Microsoft.Spark.Extensions.Azure.Synapse.Analytics/Utils/TokenLibrary.cs
src/csharp/Microsoft.Spark.sln

Create Microsoft.Spark.Extensions.Azure.Synapse.Analytics Nuget package to provide Azure.Synapse.Analytics specific functionalities for .NET for Apache Spark.

Create Microsoft.Spark.Extensions.Azure.Synapse.Analytics Nuget package

---

azure-pipelines.yml
script/package-worker.ps1

Fix release build pipeline and avoid unnecessary artifacts copies

Fix release build pipeline and avoid unnecessary artifacts copies

---

docs/building/ubuntu-instructions.md

[fix] Fix broken maven link

---

README.md
benchmark/scala/pom.xml
docs/release-notes/0.12.1/release-0.12.1.md
eng/Versions.props
src/scala/pom.xml

This PR is a preparation for a patch release (v0.12.1) to address a critical bug: #570.

Prep 0.12.1 Release

---

src/csharp/Microsoft.Spark.Worker/Processor/BroadcastVariableProcessor.cs

adding additional  FileShare.Read flag.

udf-broadcast-variable-concurrency-fix

---

examples/Microsoft.Spark.CSharp.Examples/MachineLearning/Sentiment/Program.cs
examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/Datasource.cs
src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/Index/IndexConfigTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/SparkConfTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
src/csharp/Microsoft.Spark.UnitTest/CommandSerDeTests.cs
src/csharp/Microsoft.Spark.Worker.UnitTest/CommandExecutorTests.cs
src/csharp/Microsoft.Spark.Worker/Command/RDDCommandExecutor.cs
src/csharp/Microsoft.Spark.Worker/Command/SqlCommandExecutor.cs
src/csharp/Microsoft.Spark.Worker/DaemonWorker.cs
src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs
src/csharp/Microsoft.Spark/Interop/Ipc/JvmObjectReference.cs
src/csharp/Microsoft.Spark/Network/DefaultSocketWrapper.cs
src/csharp/Microsoft.Spark/RDD.cs
src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs

Code clean up suggested by Visual Studio. There are two remaining suggestions, but the existing code is fine because it showcases how udfs can be defined:
There is no functionality change in this PR.

Code cleanup suggested by Visual Studio

---

azure-pipelines-e2e-tests-template.yml
azure-pipelines.yml

Add more comments and cleanup azure pipeline yml configs

Add comments and cleanup azure pipeline

---

eng/Versions.props

General cleanup. These should not be necessary (legacy from older restore methods)

Remove unnecessary RestoreSources

---

azure-pipelines.yml
src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

Add support for Spark 3.0.2  #827

Support Spark 3.0.2

---

azure-pipelines.yml

Update azure-pipelines.yml to remove master. This should finish migrating to `main` branch.

Update azure-pipelines.yml to remove master.

---

azure-pipelines-e2e-tests-template.yml
azure-pipelines.yml

In preparation for `v2.0.0`, disable all forward/backward tests.

Disable forward/backward tests in preparation for v2.0.0

---

README.md
benchmark/scala/pom.xml
docs/release-notes/2.0.0/release-2.0.0.md
eng/Versions.props
src/scala/pom.xml

This PR prepares the v2.0.0 release.

Prep 2.0.0 release

---

README.md
benchmark/scala/pom.xml
docs/release-notes/1.0.1/release-1.0.1.md
eng/Versions.props
src/scala/pom.xml

This PR prepares the v1.0.1 release.

Prep 1.0.1 release

---

azure-pipelines.yml

Fixes the issue with builds not requesting Windows machines. Apologies for my mistake the first time around!

Switch queue to demands to fix error

---

README.md
benchmark/scala/pom.xml
docs/release-notes/1.0.2/release-1.0.2.md
eng/Versions.props
src/scala/pom.xml

This PR prepares the v1.0.2 release.

Prep 1.0.2 release

---

README.md
benchmark/scala/pom.xml
docs/release-notes/2.1.1/release-2.1.1.md
eng/Versions.props
src/scala/pom.xml

This PR prepares the v2.1.1 release.

Prep v2.1.1 release

---

src/csharp/Microsoft.Spark/Microsoft.Spark.csproj

Fixes #1078 
* Update `csproj` to the latest `Newtonsoft.Json`.

Fixes #1078: update: newtonsoft.json package reference version

---

README.md
azure-pipelines-release.yml
benchmark/scala/pom.xml
docs/release-notes/2.3.0/release-2.3.0.md
eng/Versions.props
src/scala/pom.xml

Add release note for 2.3.0 release

Add release note for 2.3.0 release
